apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:    
  project: default
  source:
    repoURL: https://github.com/joaquin-solari/argocd-applications-repo.git
    path: applications
    directory:
      recurse: true
      jsonnet: {}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true